### ISSUE TITLE
Wrong PackageId in the ch.chmed16af.emediplan-0.2.0.xml file

### ISSUE THREAD

**Issue by DavidGutknecht** [ahdis/chmed20af#3]
Hello, 

I think the packageId value in the following file is wrong 
resources\implementationguide\ch.chmed16af.emediplan-0.2.0.xml
The actual value is "ch.mediplan.chmed16af", I think it should be as in ig-new.xml "ch.chmed16af.emediplan"

Best regards,
David

**Comment by oliveregger** [comment]
thanks for the feedback. will fix this in the next release 0.3.0, for 0.3.0 it is planned that chmed16af is also based on ch-emed, there will be a few changes.

**Comment by ziegm** [comment]
Thanks. This is now fixed with the new release 0.3.0. The acutal value is **ch.chmed20af.emediplan**.
